[global]
bpm = 60
soundfont = "bppt-midi/soundfont/soundfont.sf2"

[piano]
bank = 0
instrument = 0
set = "cCdDefFgGaAb"
score = "ccd.c"

[sax]
bank = 0
instrument = 0
set = "cCdDefFgGaAb"
score = "ccd.c"
