[package]
name = "bppt"
version = "0.2.3"
edition = "2021"
description = "A custom MML interpreter"
authors = ["Breval Ferrari <breee@duck.com>"]

[dependencies]
anyhow = "1.0"
derive-new = "0.5"
nom = "7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
